spring:
  application:
    name: YesSir
  datasource:
    url: jdbc:postgresql://localhost:5439/yessir
    username: yessir
    password: 1234
  jpa:
    show_sql: true
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #hibernate:
    #  ddl-aut: update
